// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC3G9_CyA7tZLAUItvkIwPz_pOSCDC-fM',
    appId: '1:481933006221:web:09eb4681f9ffb3746699c4',
    messagingSenderId: '481933006221',
    projectId: 'payano-49f04',
    authDomain: 'payano-49f04.firebaseapp.com',
    storageBucket: 'payano-49f04.firebasestorage.app',
    measurementId: 'G-WB5NCGQW0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGLNHUQoAcwNEGLBLfgLKV_TluBO8V2ck',
    appId: '1:481933006221:android:6cdec63b30a628b06699c4',
    messagingSenderId: '481933006221',
    projectId: 'payano-49f04',
    storageBucket: 'payano-49f04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBENvTRWKLGBNy99N-yGB1IIWrDUMiNVn4',
    appId: '1:481933006221:ios:44867cf8f4c74f216699c4',
    messagingSenderId: '481933006221',
    projectId: 'payano-49f04',
    storageBucket: 'payano-49f04.firebasestorage.app',
    iosBundleId: 'com.example.payanoMobile',
  );
}
